modLoader = "javafml"
loaderVersion = "[42,)"
license = "(c) 2021-${year} LDM. All rights reserved."

[[mods]]
modId = "mo_enchants"
version = "${mod_version}"
displayName = "Mo' Enchants"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/mo-enchants"
logoFile = "logo.png"
authors = "LDM"
description = '''
Adds more enchantments and curses to Minecraft!
'''

[[dependencies.mo_enchants]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version}]"
ordering = "NONE"
side = "BOTH"