modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "(c) 2021-${year} LDM. All rights reserved."

[[mods]]
modId = "mo_enchants"
version = "${mod_version}"
displayName = "Mo' Enchants"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/mo-enchants"
logoFile = "logo.png"
authors = "LDM"
description = '''
Adds more enchantments and curses to Minecraft!
'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.mo_potions]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mo_potions]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version}]"
ordering = "NONE"
side = "BOTH"